// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUz8VjFxli6rL82sxmql12n6DFDuR0b8',
    appId: '1:612376194301:web:9b5ec757254874c07a2294',
    messagingSenderId: '612376194301',
    projectId: 'stylesnap',
    authDomain: 'stylesnap.firebaseapp.com',
    storageBucket: 'stylesnap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNtuTN1m9alsyJ3WMEyTXTxMRQh3M-lgo',
    appId: '1:612376194301:android:e96764838f50245e7a2294',
    messagingSenderId: '612376194301',
    projectId: 'stylesnap',
    storageBucket: 'stylesnap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66X1-UF3sXPE4ns_rv4a_DhDWuAUq6Cs',
    appId: '1:612376194301:ios:b73c54c3590aa2ce7a2294',
    messagingSenderId: '612376194301',
    projectId: 'stylesnap',
    storageBucket: 'stylesnap.appspot.com',
    iosBundleId: 'com.example.stylesnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66X1-UF3sXPE4ns_rv4a_DhDWuAUq6Cs',
    appId: '1:612376194301:ios:a9ee2af2f3fde0ce7a2294',
    messagingSenderId: '612376194301',
    projectId: 'stylesnap',
    storageBucket: 'stylesnap.appspot.com',
    iosBundleId: 'com.example.stylesnap.RunnerTests',
  );
}
